### ISSUE TITLE
need HELP

### ISSUE THREAD

**Issue by wermaxta** [A-mIn3/Lantester#1]
Hi i have problem with lantester.py
When i type python lantester.py -h i get this error 
Traceback (most recent call last):
  File "lantester.py", line 4, in <module>
    logging.getLogger("scapy.runtime").setLevel(logging.ERROR)
NameError: name 'logging' is not defined

My OS is Linux kali 4.9.0-kali4-amd64 #1 SMP Debian 4.9.25-1kali1 (2017-05-04) x86_64 GNU/Linux
python is Python 2.7.13
Thank you :)

**Comment by A-mIn3** [comment]
Hi , 
  This has to do with the logging module. It is used  to disable scapy logging on console . 
  Make sure you import all the required modules.
